### ISSUE TITLE
Uncaught TypeError: Utils.getTarget is not a function

### ISSUE THREAD

**Issue by ghost** [TomMalbran/games#1]
Uncaught TypeError: Utils.**getTarget** is not a function

getTarget is not defined in Utils.js

**Comment by TomMalbran** [comment]
Added. I had a bunch of changes that I forgot commit, hehe.

Anyway since I was using this code for fun, is now all in ES6, since I like the new syntax, is a lot cleaner.

**Comment by ghost** [comment]
Great code you got there! Thanks for the games!

**Comment by ghost** [comment]
getTarget: function(e){
            return e.target;
        }

need something like this on your Util.js but I guess you have already push your commit. Thanks!

**Comment by TomMalbran** [comment]
Thanks.

Actually getTarget doesn't do that, since I can just use e.target for that. Probably the name of the function is not the best. Is closer in what it does to jQuery.closest() function but more specific for my use case.
