### ISSUE TITLE
Great Mini games but a couple of issues.

### ISSUE THREAD

**Issue by DestructiveBurn** [TomMalbran/games#2]
Wonderful, Lightweight and clean looking UI 

First Issue. Defender doesn't work.  You cannot click on the buttons. So I have no idea how the gameplay is on that.  
Second Issue.  High Scores only seem to be local to that browser only and won't show for anyone else. 

I use this on my website for the Famous Konami Code ↑↑↓↓← →← → B A
Hope to see this fixed :)

**Comment by TomMalbran** [comment]
I believe that all the Defender issues are resolved.

I will not create a server or anything like that to store HighScores. I do not want to manage that.

Is cool that you found these mini game clones great.
