### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by deepak-ariceum** [TomMalbran/games#5]
Can you please add installation instructions for the project? 
Post cloning the project. I'm not sure what to do. I'm a noob, please excuse.

**Comment by TomMalbran** [comment]
The project requires no installation as it is just HTML, CSS and JavaScript. You can just open the index.html file in the main directory in any browser and it works. Or you can open the index.html file in each game. If you want to upload it to a server, just upload all the files

**Comment by deepak-ariceum** [comment]
No, I did try that first. It doesn't work. I'm getting the below error. Shall I install a http-client and try instead?
[Error] Origin null is not allowed by Access-Control-Allow-Origin. Status code: 0

I have resolved by starting a http server from the main folder of the project.
python3 -m http.server
& then open - http://localhost:8000
